env:
  es6: true
  browser: true
  jest: true
root: true
extends:
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:jsx-a11y/recommended"
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
ignorePatterns:
  - node_modules
  - dist
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: "module"
plugins:
  - "jsx-a11y"
  - "react"
  - "react-hooks"
  - "import"
  - "@typescript-eslint"
  - "prettier"
  - jest
globals:
  process: true
overrides:
  - files:
      - "*.test.js"
      - "*.spec.js"
    env:
      jest: true
    plugins:
      - jest
    extends:
      - "plugin:jest/recommended"
settings:
  react:
    version: "detect"
    pragma: "React"
  "import/parsers":
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
rules:
  "import/order":
    - "error"
    - groups:
        - "builtin"
        - "external"
        - "internal"
        - "parent"
        - "sibling"
        - "index"
      newlines-between: always
      alphabetize:
        order: "asc"
        caseInsensitive: true
  "jsx-a11y/no-autofocus": "off"
  "import/default": "off"
  "react/jsx-sort-props": "error"
  "react/react-in-jsx-scope": "off"
  "react/prop-types": "off"
  "padding-line-between-statements":
    - "error"
    - blankLine: "always"
      prev:
        - "const"
        - "let"
        - "var"
      next: "*"
    - blankLine: "any"
      prev:
        - "const"
        - "let"
        - "var"
      next:
        - "const"
        - "let"
        - "var"
    - blankLine: "always"
      prev: "*"
      next: "return"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/camelcase": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "no-undef": "off"
  "@typescript-eslint/no-use-before-define": "off"
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": "error"
  "spaced-comment":
    - "warn"
    - "always"
    - exceptions:
        - "-"
        - "+"
  "@typescript-eslint/no-explicit-any": "warn"
  import/namespace:
    - off
  prettier/prettier:
    - "error"
    - printWidth: 80
      tabWidth: 2
      singleQuote: true
      quoteProps: "as-needed"
      trailingComma: "none"
      bracketSpacing: true
      semi: false
      useTabs: false
      proseWrap: "never"
